# Generated by Django 3.2.6 on 2021-09-29 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_alter_carts_wallpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='wallpaper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.wallpaper'),
        ),
    ]
