# Generated by Django 3.2.6 on 2021-09-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0012_alter_carts_wallpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
