# Generated by Django 3.2.6 on 2021-09-22 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('profile_pic', models.FileField(default='static/images/default_user.png', upload_to='static/profile')),
                ('content_image', models.FileField(default='static/images/default_cd.png', upload_to='static/uploads')),
                ('content_audio', models.FileField(default='', upload_to='static/audio')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
