# Generated by Django 3.2.6 on 2021-09-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210923_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='username',
        ),
    ]
